---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: traefik/whoami
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: whoami

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: whoami
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # Use your ClusterIssuer/Issuer name here
spec:
  ingressClassName: nginx
  rules:
  - host: whoami.rev.griesberg3.de # Replace with your domain
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: whoami-service
            port:
              number: 80
  tls:
  - hosts:
    - whoami.rev.griesberg3.de # Replace with your domain
    secretName: whoami-tls-secret # cert-manager will store the certificate here
